# Backend Dockerfile
FROM node:22-alpine

# directorio de trabajo dentro del contenedor
WORKDIR /app

# copiar solo archivos de dependencias
COPY package*.json ./


# copiar el resto del código
COPY . .

# exponer puerto del servidor
EXPOSE 3000

# comando por defecto al iniciar el contenedor
CMD ["npm", "run", "dev"]